# Generated by Django 5.1 on 2025-10-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_visita', models.DateField()),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('lugar_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='feed.lugarturistico')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('reaccion', models.IntegerField(default=0)),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='usuarios.turista')),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='feed.resena')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='fotos_resenas/')),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografias', to='feed.resena')),
            ],
        ),
    ]
