# Generated by Django 5.1 on 2025-10-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_resena_fecha_visita'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.publicacion')),
                ('turista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.turista')),
            ],
            options={
                'unique_together': {('turista', 'publicacion')},
            },
        ),
    ]
