# Generated by Django 5.1 on 2025-10-15 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.publicacion'),
        ),
    ]
