# Generated by Django 5.1 on 2025-10-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_like_publicacion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('publicacion', 'turista')},
        ),
    ]
