# Generated by Django 5.1 on 2025-11-11 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugarturistico',
            options={'verbose_name_plural': 'Lugares Turísticos'},
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lugarturistico',
            name='categoria',
            field=models.CharField(choices=[('restaurante', 'Restaurante'), ('bar', 'Bar'), ('cafe', 'Café'), ('museo', 'Museo'), ('parque', 'Parque'), ('monumento', 'Monumento'), ('iglesia', 'Iglesia'), ('hotel', 'Hotel'), ('centro_comercial', 'Centro Comercial'), ('tienda', 'Tienda'), ('entretenimiento', 'Entretenimiento'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
        migrations.AlterField(
            model_name='lugarturistico',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lugarturistico',
            name='ubicacion',
            field=models.CharField(max_length=250),
        ),
    ]
