# Generated by Django 5.1 on 2025-11-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_notificacion'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='perfil_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_perfil', to='usuarios.turista'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('like', 'Like en tu publicación'), ('comentario', 'Comentario en tu publicación'), ('nueva_publicacion', 'Nueva publicación de alguien que sigues'), ('nuevo_seguidor', 'Nuevo seguidor')], max_length=20),
        ),
    ]
